settings:
  name: ONTAP FlexArray
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
    - title: ONTAP FlexArray Docs
      url: "/index.html"
    - section: implement-e-series
    - section: implement-third-party
    - section: install
    - title: Legal Notices
      url: /reference_legal_notices.html

product-family: 
  name: ONTAP
  repo: ontap-family
  
