---
permalink: install/concept_available_lun_security_methods.html
sidebar: sidebar
keywords: 
summary: 'Various LUN security methods help you designate which hosts can access particular array LUNs. You can use port-level security or LUN security products, or dedicate a storage for use by ONTAP systems.'
---
= Available LUN security methods
:icons: font
:imagesdir: ../media/

[.lead]
Various LUN security methods help you designate which hosts can access particular array LUNs. You can use port-level security or LUN security products, or dedicate a storage for use by ONTAP systems.

== Port-level security

You can use port-level security to present only the array LUNs for a particular host. That port then becomes dedicated to that host.

Not all storage arrays support port-level security. Some storage arrays present all LUNs on all ports by default, and they do not provide a way to restrict the visibility of LUNs to particular hosts. For these arrays, you must either use a LUN security product or dedicate the storage array to the ONTAP system. You should check your storage array documentation to determine whether your storage array supports port-level security.

== LUN security products

You can use a LUN security product to control hosts that are zoned to the same port so that they can access only specific array LUNs over that port. This prevents other hosts from accessing those same array LUNs by masking them from the other hosts.

== Dedicate the storage array for ONTAP use

You can dedicate the storage array for use by ONTAP systems. In this case, no hosts other than the ONTAP systems are connected to the storage array.

You should use both zoning and LUN security to achieve added protection and redundancy for the ONTAP systems.

In addition to following the LUN security methods, you should also check for any additional details regarding LUN security for your vendor's storage arrays. Some storage arrays must be dedicated for use by ONTAP systems.

*Related information*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html[FlexArray virtualization implementation for third-party storage]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html[FlexArray virtualization implementation for NetApp E-Series storage]
