---
permalink: install/concept_considerations_for_checking_the_checksum_type_of_spare_array_luns.html
sidebar: sidebar
keywords: 
summary: 'You must account for certain considerations related to checksum types when adding spare array LUNs to aggregates. For example, if you plan to add a spare array LUN to an aggregate by specifying its name, you must ensure that array LUN and the aggregate have the same checksum type.'
---
= Checksum type considerations for adding spare array LUNs to aggregates
:icons: font
:imagesdir: ../media/

[.lead]
You must account for certain considerations related to checksum types when adding spare array LUNs to aggregates. For example, if you plan to add a spare array LUN to an aggregate by specifying its name, you must ensure that array LUN and the aggregate have the same checksum type.

The following are some checksum type considerations for adding spare array LUNs to aggregates:

* You cannot mix array LUNs of different checksum types in an array LUN aggregate.
* If you specify a number of spare array LUNs to be added to an aggregate, ONTAP by default selects the array LUNs of the same checksum type as the aggregate.
* Array LUNs of the zoned checksum type when added to an existing zoned checksum aggregate continue to be zoned checksum array LUNs.
* Zoned checksum spare array LUNs added to an Advanced Zone Checksum (AZCS) type aggregate use the AZCS checksum scheme.

[NOTE]
====
You can check the checksum type of the spare array LUNs by using the storage disk show command.For more information about the command, see the man pages.

====
