---
permalink: install/concept_zoning_recommendation_for_a_configuration_with_storage_arrays.html
sidebar: sidebar
keywords: 
summary: 'The recommended type of zoning for a configuration with storage arrays is 1:1 zoning. With 1:1 zoning, each zone contains a single FC initiator port and a single storage array target port.'
---
= Zoning recommendation for a configuration with storage arrays
:icons: font
:imagesdir: ../media/

[.lead]
The recommended type of zoning for a configuration with storage arrays is 1:1 zoning. With 1:1 zoning, each zone contains a single FC initiator port and a single storage array target port.

The benefits of creating 1:1 zoning are as follows:

* You limit the number of ports over which a specific array LUN can be accessed.
* There are discovery and boot time improvements because the FC initiators ONTAP systems do not attempt to discover each other.

*Related information*

xref:concept_example_of_zoning_in_a_configuration_with_storage_arrays.adoc[Example of zoning in a configuration with storage arrays]

xref:concept_example_configuration_shared_fc_initiator_ports.adoc[Example configuration: shared FC initiator ports]
