---
permalink: install/concept_support_for_metrocluster_configurations_that_can_use_array_luns.html
sidebar: sidebar
keywords: 
summary: 'Before you set up a MetroCluster configuration with array LUNs, you must ensure that the ONTAP systems and the storage used in the configuration follow basic supportability requirements.'
---
= Requirements for MetroCluster configurations with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
Before you set up a MetroCluster configuration with array LUNs, you must ensure that the ONTAP systems and the storage used in the configuration follow basic supportability requirements.

The basic requirements for supporting MetroCluster configurations with array LUNs are as follows:

* You can use both V-Series systems and FAS systems with support for array LUNs in MetroCluster configurations.
+
However you must ensure that all the ONTAP systems used in a MetroCluster configuration are of the same model.

* The ONTAP systems can use native disks only, LUNs on storage arrays only, or both.
* If you are setting up a MetroCluster configuration with both native disks and array LUNs, you must use FC-to-SAS bridges and native disks supported by those bridges.
* The ONTAP systems and storage arrays must be identified in the _Interoperability Matrix_ as being supported in MetroCluster configurations.

*Related information*

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

link:Fabric-attached MetroCluster installation and configurationhttps://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration]

link:Stretch MetroCluster installation and configurationhttps://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/index.html[Stretch MetroCluster installation and configuration]
