---
permalink: install/concept_considerations_when_planning_for_disk_ownership.html
sidebar: sidebar
keywords: 
summary: 'If you are deploying multiple ONTAP systems for use with array LUNs, you must determine which system owns which array LUNs. Disk ownership ensures that only the ONTAP system that owns a particular array LUN can read data from and write data to the array LUN.'
---
= Considerations when planning for disk ownership
:icons: font
:imagesdir: ../media/

[.lead]
If you are deploying multiple ONTAP systems for use with array LUNs, you must determine which system _owns_ which array LUNs. Disk ownership ensures that only the ONTAP system that owns a particular array LUN can read data from and write data to the array LUN.

You should consider the following when planning which system will own which array LUNs:

* The maximum assigned device limit supported by your platform
+
The _Hardware Universe_ shows the maximum assigned device limit that is supported for different platforms. This is a hard-coded limit. If your system uses both array LUNs and disks, this maximum limit is the maximum of disks and array LUNs combined. You must account for both types of storage when determining how many array LUNs and disks you can assign to a system.

* The amount of load that you expect to be generated by different applications used in your environment
+
Some types of applications are likely to generate a lot of requests, whereas other applications (for example, archival applications) generate fewer requests. You might want to consider weighing ownership assignments based on expected load from specific applications.

*Related information*

xref:concept_systems_that_can_use_array_luns_on_storage_arrays.adoc[ONTAP systems that can use array LUNs on storage arrays]

xref:concept_how_array_luns_become_available_for_ontap_storage_use.adoc[How array LUNs become available for ONTAP storage use]

https://hwu.netapp.com[NetApp Hardware Universe]
