---
permalink: install/concept_back_end_configuration_errors_detected_by_ontap_commands.html
sidebar: sidebar
keywords: 
summary: 'The storage errors show command provides details, at the array LUN level, about common back-end configuration errors. You can also use the storage disk error show and the storage disk show -errors commands to view the errors.'
---
= Back-end configuration errors detected by ONTAP commands
:icons: font
:imagesdir: ../media/

[.lead]
The storage errors show command provides details, at the array LUN level, about common back-end configuration errors. You can also use the storage disk error show and the storage disk show -errors commands to view the errors.

You must fix the back-end configuration errors identified by these commands before you can configure ONTAP to work with array LUNs.
[NOTE]
====
While the storage errors show command provides error details pertaining to only array LUNs, the storage disk error show and the storage disk show -errors commands can provide error details related to array LUNs as well as disks.
====

When there is a back-end configuration error that would prevent the devices in your configuration from working together, the storage array config show command instructs you to run storage errors show to obtain the details of the error.

== List of back-end configuration errors

The storage errors show, storage disk error show, and storage disk show -errors commands can help identify back-end configuration errors such as the following:

* There are fewer than two paths to an array LUN.
* All paths to an array LUN are to the same storage array controller.
* Two array LUNs are presented with the same LUN ID.
* The LUN IDs for the same LDEV do not match on all target ports over which the LDEV will be visible.
* The array LUN exceeds the ONTAP maximum LUN size.
* The array LUN does not meet the ONTAP minimum LUN size.
* The block size of an array LUN is invalid.
* An access LUN is presented to ONTAP.

== Output examples displaying the back-end configuration errors

The storage errors show output is grouped by storage array (if there is more than one storage array behind the ONTAP system). The name and unique identifier (UID) of an array LUN are shown, when applicable.

The following output example shows one type of error--only one path to an array LUN. This is an error because ONTAP requires two paths to an array LUN.

[NOTE]
====
Four paths to an array LUN are supported for clustered configurations.
====

The following example shows the errors returned by the storage errors show command because of only a single path configured to an array LUN:

----

systemf47ab::*> storage errors show
DGC-1.51         onepath           DGC-1.51 (6006016044d03500ae553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.54         onepath           DGC-1.54 (6006016044d03500b4553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.55         onepath           DGC-1.55 (6006016044d03500b6553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.56         onepath           DGC-1.56 (6006016044d03500b8553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.57         onepath           DGC-1.57 (6006016044d03500ba553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.58         onepath           DGC-1.58 (6006016044d03500bc553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
----

The following example shows similar errors returned by the storage disk show -errors command:

----

systemf47ab::*> storage disk show -errors
DGC-1.2          onepath           DGC-1.2 (6006016044d03500e0720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.3          onepath           DGC-1.3 (6006016044d03500e2720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.4          onepath           DGC-1.4 (6006016044d03500e3720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.5          onepath           DGC-1.5 (6006016044d03500e4720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.6          onepath           DGC-1.6 (6006016044d03500e5720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.7          onepath           DGC-1.7 (6006016044d03500e6720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
----

*Related information*

xref:concept_systems_that_can_use_array_luns_on_storage_arrays.adoc[ONTAP systems that can use array LUNs on storage arrays]

xref:concept_situations_not_identified_by_commands_that_check_back_end_configuration.adoc[Situations not identified by commands that check back-end configuration]

xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[LUN IDs for the same LDEV do not match]

xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Fewer than two paths to an array LUN]

xref:concept_required_number_of_paths_to_an_array_lun.adoc[Required number of paths to an array LUN]

xref:task_checking_for_back_end_configuration_errors_preventing_system_operation.adoc[Checking for back-end configuration errors preventing system operation]
