---
permalink: install/concept_guidelines_for_specifying_the_appropriate_target_queue_depth.html
sidebar: sidebar
keywords: guidelines, specify, appropriate, target, queue, depth
summary: "You need to consider the impact of all the initiators accessing the storage array port when you are planning the configuration for a specific ONTAP system or a specific host that does not run ONTAP."
---
= Guidelines for specifying the appropriate target queue depth
:icons: font
:imagesdir: ../media/

[.lead]
You need to consider the impact of all the initiators accessing the storage array port when you are planning the configuration for a specific ONTAP system or a specific host that does not run ONTAP.

If your deployment includes more than one initiator on a target port, you need to consider the total number of commands sent to a target port by all initiators when setting the target queue depth.

Guidelines for specifying the appropriate target queue depth are as follows:

* Do not configure a value of 0 (zero).
+
A value of 0 means that there is no limit on the outstanding commands.

* Consider the volume of commands that specific initiators would be likely to send to the target port.
+
You could then configure higher values for initiators likely to send a greater number of requests and a lower value for initiators likely to send a lesser number of requests.

* Configure hosts that do not run ONTAP according to the guidelines provided for those hosts.
* Consider setting the target queue depth on a per-target-port basis when workloads differ across ports.
