---
permalink: install/concept_target_port_utilization_policy_settings.html
sidebar: sidebar
keywords: 
summary: 'ONTAP can detect events of resource contention, such as I/O queue being full, commands being timed out or HBA resource getting exhausted, on a target port.'
---
= Target port utilization policy settings
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP can detect events of resource contention, such as I/O queue being full, commands being timed out or HBA resource getting exhausted, on a target port.

You can set the target port utilization policies by using the storage array port modify command if you detect such events on a given array target port.

The following table describes the two utilization policies associated with a target port:

|===
| Policy| Description
a|
normal
a|
When ONTAP detects target port resource contention on a given array target port, it reduces the targets port's queue depth and throttles I/O to the target port. In this mode, the reduction of the target port queue depth is lesser than the defer policy for each target port resource contention event. The subsequent rise in the target port queue depth is faster than the defer policy. normal is the default policy.
a|
defer
a|
When ONTAP detects target port resource contention on a given array target port, it reduces the target port's queue depth and throttles I/O to the target port. In this mode, the reduction of the target port queue depth is greater than the normal policy for each target port resource contention event. The subsequent rise in the target port queue depth is slower than the normal utilization policy.
|===

== Output examples to view and modify array target port utilization policies

The following command displays the target port utilization policy associated with an array target port:

----
vgv3170_jon::> storage array port show -wwnn 2703750270235
        Array Name: HITACHI_DF600F_1
              WWNN: 2703750270235
              WWPN: 2703750270235
   Connection Type: fabric
       Switch Port: vgbr300s89:9
        Link Speed: 4 GB/s
   Max Queue Depth: 1024
Utilization Policy: defer
                              LUN                                        Link
Node              Initiator  Count   IOPS    KB/s    %busy    %waiting   Errs
----------------  ---------  -----  ------  ------  -------  ----------  ----
     vgv3170f54a         0a      2       50   1956       85           0     0
     vgv3170f54b         0a      2      350  15366      100          40     0
----

By default, the I/O policy for a given array target port is normal. You can modify the I/O policy associated with the port by running the following command:

----
vgv3070f50ab::> storage array port modify -wwpn 50014380025d1509 -utilization-policy ?



normal      This policy aggressively competes for target port resources, in effect competing with other hosts.
             (normal)

defer      	This policy does not aggressively compete for target port resources, in effect deferring to other hosts.

vgv3070f50ab::> storage array port modify -wwpn 50014380025d1509 -utilization-policy defer
1 record updated.
----
