---
permalink: install/concept_requirements_for_v_series_fc_initiator_port_usage.html
sidebar: sidebar
keywords: requirements, use, fc initiator, ports
summary: "If you want to use FC initiator ports in an ONTAP configuration with array LUNs, you must follow specific requirements for port pair redundancy, port settings for HBAs, connecting to target ports, array LUN limits, and connecting to different storage and devices."
---
= Requirements for using FC initiator ports
:icons: font
:imagesdir: ../media/

[.lead]
If you want to use FC initiator ports in an ONTAP configuration with array LUNs, you must follow specific requirements for port pair redundancy, port settings for HBAs, connecting to target ports, array LUN limits, and connecting to different storage and devices.
[options="header"]
|===
| For this feature...| The requirements are...
a|
Port pair redundancy
a|
You must use redundant FC initiator port pairs while connecting an ONTAP system to array LUNs.

a|
Port setting for HBAs
a|
You must set all the HBAs used to access disks or array LUNs as initiator ports.
a|
Connecting to storage array target ports
a|
You can connect the same FC initiator port to multiple target ports on the storage array.

You can connect a maximum of two FC initiator ports to a single target port.

a|
Array LUN limits
a|
There are limits on how many array LUNs can be visible over an FC initiator port. These limits vary with ONTAP releases.

a|
Connecting to different storage and devices
a|
You must use a separate FC initiator port to connect the ONTAP system to each of the following:

* Disk shelves
* Array LUNs
* Tape devices

If the ONTAP system does not have enough internal ports for your requirement, you must order an additional HBA.

|===
