---
permalink: install/reference_factors_impacting_the_required_number_of_array_luns.html
sidebar: sidebar
keywords: 
summary: 'While planning for ONTAP use of array LUNs, you must consider factors such as array LUN size, ONTAP overhead, and checksum type that impact the number of array LUNs required in your ONTAP environment.'
---
= Factors impacting the required number of array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
While planning for ONTAP use of array LUNs, you must consider factors such as array LUN size, ONTAP overhead, and checksum type that impact the number of array LUNs required in your ONTAP environment.

You should consider the following when determining the required number of array LUNs:

* The smaller the array LUNs, the more LUNs you require for the storage.
+
Ideally, creating one large array LUN from a given storage array RAID group is recommended.

* Device limits define the maximum number of disks and array LUNs that can be assigned to an ONTAP system.
+
The _Hardware Universe_ contains information about device limits.

* The more usable space in an array LUN, the fewer array LUNs are required.
+
The amount of usable space in an array LUN is determined by the space that ONTAP requires, checksum type, and additional factors such as space required for optional Snapshot reserves.

* Different applications generate different loads.
+
When determining the assignment of array LUNs to ONTAP systems, you must consider what the storage will be used for and the number of requests that are likely to be generated by different applications.
