---
permalink: install/reference_reasons_for_fewer_array_lun_groups_than_expected.html
sidebar: sidebar
keywords: reasons, fewer, array, lun, groups, expected, resolve, issue
summary: "When validating the back-end configuration, you need to check the storage array config show output to determine whether the number of array LUN groups in the output is what you intended."
---
= Reasons for fewer array LUN groups than expected
:icons: font
:imagesdir: ../media/

[.lead]
When validating the back-end configuration, you need to check the `storage array config show` output to determine whether the number of array LUN groups in the output is what you intended.

== Explanation

The most likely cause for fewer LUN groups than expected is that the LDEV-to-LUN mapping is the same for both FC initiator port pairs on the ONTAP system. If the LDEV-to-LUN mapping is the same for both FC initiator port pairs, the `storage array config show` output shows one less LUN group than expected.

The following `storage array config show` output shows only one array LUN group due to both FC initiator port pairs being mapped to the same target port pair:

----

mysystem1::> storage array config show

         LUN   LUN
Node     Group Count Array Name  Array Target Ports      Switch Port    Initiator
------   ----- ----- ---------- -------------------      -----------    ---------

mysystem1  0     2   DGC_RAID5_1  20:1A:00:a0:b8:0f:ee:04  vnbr200es25:5   0a
                                  20:2A:00:a0:b8:0f:ee:04  vnci9124s53:6   0c
                                  20:1A:00:a0:b8:0f:ee:04  vnbr200es25:5   0b
                                  20:2A:00:a0:b8:0f:ee:04  vnci9124s53:6   0d
----

By looking at the Array Target Ports column, you can see the same target port more than once within the LUN group, and each occurrence has a different initiator.

* Initiators 0a and 0b both have access to storage array port 1A.
* Initiators 0c and 0d both have access to storage array port 2A.

== Resolving the issue

ONTAP does not flag this as an error because an ONTAP system can operate when the LDEV-to-LUN mapping is the same for both FC initiator port pairs. However, multiple FC initiators to the same target port is not supported. You should fix the mapping so that your ONTAP system follows a supported configuration, and so that you have the number of LUN groups that you intended.

If you want to fix this issue, do the following:

. On the storage array, fix the mapping so that the FC initiator port pair mapping is no longer the same for both FC initiator port pairs on the ONTAP system.
. On the ONTAP system, run `storage array config show` again and confirm that the number of LUN groups that you expected are shown and that FC initiator port pairs are not accessing the same target ports.
