---
permalink: install/task_getting_started_with_troubleshooting.html
sidebar: sidebar
keywords: get, started, troubleshoot, ontap, configuration, array, luns
summary: "While troubleshooting an ONTAP configuration with array LUNs, you should follow a systematic approach to determine the cause of the issue."
---
= Getting started with troubleshooting an ONTAP configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
While troubleshooting an ONTAP configuration with array LUNs, you should follow a systematic approach to determine the cause of the issue.

This procedure suggests an order for approaching troubleshooting.

[NOTE]
====
As you continue with the troubleshooting steps, you should save any information that you gather about the issue so that you can provide this information to technical support in the case of an escalation.
====
.Steps
. Determine whether the issue is with the _front end_ (an ONTAP issue that affects all the corresponding platforms) or the _back end_ (an issue with the switch or storage array configuration).
+
For example, if you are trying to use an ONTAP feature and it is not working as you expected, the issue is likely to be with the front end.

. Take appropriate action to address the issue, depending on its nature:
+
[options="header"]
|===
| If the ONTAP configuration has a...| Then do this...
a|
Front end issue
a|
Proceed with troubleshooting the ONTAP feature by following instructions in the ONTAP guides.

https://docs.netapp.com/us-en/ontap/index.html[ONTAP 9 Documentation^]
a|
Back end issue
a|

 .. Check the Interoperability Matrix to ensure that the following are supported: configuration, storage array, storage array firmware, switch, and switch firmware.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]

 .. Use the `storage array config show` command to check whether there are any common back-end configuration errors that the system can detect.
+
If ONTAP detects a back-end configuration error, you must run the `storage errors show` command to obtain details about the error.

+
|===

. If the cause of the issue is still not clear, check the following sources to ensure that your system is compliant with the requirements for working with storage arrays:
 ** xref:concept_verifying_an_installation_with_storage_arrays.adoc[Verifying an installation with storage arrays]
 ** https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html[FlexArray virtualization implementation for third-party storage]
 ** https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html[FlexArray virtualization implementation for NetApp E-Series storage]
 ** https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
 ** https://hwu.netapp.com[NetApp Hardware Universe^]
. If you still need help resolving the issue, contact technical support.

// 2022-06-16, BURT 1485034
