---
permalink: install/task_verifying_if_the_back_end_configuration_matches_the_expected_output.html
sidebar: sidebar
keywords: verify, back-end, configuration, matches, intended, configuration
summary: "After resolving the back-end configuration errors detected by storage errors show, you must check whether the existing back-end configuration matches the configuration you intended, and fix issues arising out of any mismatch."
---
= Verifying that the back-end configuration matches the intended configuration
:icons: font
:imagesdir: ../media/

[.lead]
After resolving the back-end configuration errors detected by storage errors show, you must check whether the existing back-end configuration matches the configuration you intended, and fix issues arising out of any mismatch.

.Steps
. Enter the following command: `storage array config show`
+
The storage array config show output groups information about LUN groups, LUN counts, and paths by storage array, as the following example for an HA pair shows:
+
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count  Array Name      Array Target Port   Initiator
------------ ----- ----- ---------------  ------------------  ---------
mysystem1a    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
mysystem1b    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
8 entries were displayed.
----

. Check the storage array config show output for each problem statement in the following table, and refer to the appropriate information for solution.
+
[options="header"]
|===
| If you find this problem...| See this information...
a|
Empty LUN groups
a|
xref:reference_reasons_for_no_luns_in_the_array_lun_group.adoc[Reasons for no LUNs in the array LUN group]
a|
Missing expected storage arrays
a|
xref:reference_reasons_storage_arrays_are_missing_from_command_output.adoc[Reasons you might not see all storage arrays you expected]
a|
More array LUN groups than expected
a|
xref:reference_reasons_for_more_array_lun_groups_than_expected.adoc[Reasons for more array LUN groups than expected]
a|
Fewer array LUN groups than expected
a|
xref:reference_reasons_for_fewer_array_lun_groups_than_expected.adoc[Reasons for fewer array LUN groups than expected]
a|
Array LUN groups do not show the number of LUNs expected
a|
xref:reference_reasons_for_the_incorrect_number_of_luns_in_array_lun_groups.adoc[Reasons for the incorrect number of LUNs in array LUN groups]
a|
Fewer paths than expected
a|
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Fewer than two paths to an array LUN]
a|
More paths than expected
a|
xref:reference_reasons_for_more_paths_to_an_array_lun_than_expected.adoc[Reasons for more paths to an array LUN than expected]
|===
