---
permalink: install/task_changing_array_lun_size_or_composition.html
sidebar: sidebar
keywords: change, array, lun, size, composition
summary: "Reconfiguring the size or composition of an array LUN must be done on the storage array. If an array LUN has already been assigned to an ONTAP system, you must use ONTAP to change the state of the array LUN to unused before the storage array administrator can reconfigure it."
---
= Changing array LUN size or composition
:icons: font
:imagesdir: ../media/

[.lead]
Reconfiguring the size or composition of an array LUN must be done on the storage array. If an array LUN has already been assigned to an ONTAP system, you must use ONTAP to change the state of the array LUN to unused before the storage array administrator can reconfigure it.

*What you'll need*

The array LUN must be a spare array LUN before you can change its state to unused.

.Steps
. On the ONTAP system, enter the following command to remove ownership information: `storage disk removeowner  -disk arrayLUNname`
. On the storage array, complete the following steps:
 .. Unmap (unpresent) the array LUN from the ONTAP systems so that they can no longer see the array LUN.
 .. Change the size or composition of the array LUN.
 .. If you want ONTAP to use the array LUN again, present the array LUN to the ONTAP systems again.
+
At this point, the array LUN is visible to the FC initiator ports to which the array LUN was presented, but it cannot be used by any ONTAP systems yet.
. Enter the following command on the ONTAP system that you want to be the owner of the array LUN: `storage disk assign -disk arrayLUNname -owner nodename`
+
After the ownership information is removed, the array LUN cannot be used by any ONTAP system until the array LUN is assigned again to a system. You can leave the array LUN as a spare or add it to an aggregate. You must add the array LUN to an aggregate before the array LUN can be used for storage.
