---
permalink: install/task_displaying_target_port_queue_depth_statistics_clustered_data_ontap_8_2_and_later.html
sidebar: sidebar
keywords: 
summary: 'If you suspect that a target queue depth setting is causing performance issues on your storage array, you should check the value that is set for the queue depth and check the state of requests on the FC initiator ports.'
---
= Displaying target queue depth statistics
:icons: font
:imagesdir: ../media/

[.lead]
If you suspect that a target queue depth setting is causing performance issues on your storage array, you should check the value that is set for the queue depth and check the state of requests on the FC initiator ports.

There are different levels of detail that you can access to determine whether there are problems processing requests on target ports. The following steps describe how to determine the current setting for the target port queue depth, determine whether there are requests waiting on the ports, and display detailed port statistics to help you understand the workload on the port.

. Use the storage array show command with the -instance parameter to show the current value of the target port queue depth.
+
----
> set advanced
> storage array show -instance

Name: HP2
                 Prefix: HP-2
                 Vendor: HP
                  Model: HSV300
                options:
          Serial Number: 50014380025d1500
Target Port Queue Depth: 512
        LUN Queue Depth: 32
        Upgrade Pending: false
    Optimization Policy: eALUA
               Affinity: aaa
             Error Text: -
----

. Use the storage array port show -fields max-queue-depth command to show the queue depth setting for each port on the storage array.
+
----
> set advanced
> storage array port show -fields max-queue-depth

name            wwnn             wwpn             max-queue-depth
--------------- ---------------- ---------------- ---------------
EMC_SYMMETRIX_1 50060480000001a0 50060480000001a0 -
EMC_SYMMETRIX_1 50060480000001a1 50060480000001a1 -
EMC_SYMMETRIX_1 50060480000001b0 50060480000001b0 -
EMC_SYMMETRIX_1 50060480000001b1 50060480000001b1 256
----
+
A value of "`-`"for Max Queue Depth indicates that the port does not have a specific max queue depth setting and is using the value set at the storage array level.

. Use the storage array port show command to display performance information about storage array target ports.
+
The results of this command help you determine whether there are performance problems related to the ports. The %busy and %waiting values provide a high-level view of the performance on a port. If these values show a high percentage of requests waiting to be processed or show that the port is busy for a great percentage of time, then you might want to investigate further into the state of the port.
+
----

vgv3070f51::*> storage array port show

Array Name: HP2
WWNN: 50014380025d1500
WWPN: 50014380025d1508
Connection Type: fabric
Switch Port: vgbr300s70:9
Link Speed: 4   GB/s
Max Queue Depth: -
                              LUN                                 Link
Node       Initiator  Count   IOPS    KB/s    %busy    %waiting   Errs
---------  ---------  -----  ------  ------  -------  ----------  ----
vgv51-02       0a     21       2      53        0           0     0
vgv51-01       0a     21       2      48        1           0     0
----

. You can obtain more detailed information about ports by using the storage array port show -fields command with the average-latency-per-iop, average-pending, average-waiting, max-pending, or max-waiting fields.
