---
permalink: install/task_obtaining_wwns_manually.html
sidebar: sidebar
keywords: obtain, wwpns, manually
summary: "If the ONTAP system is not connected to the SAN switch, you need to obtain the World Wide Port Names (WWPNs) of the system’s FC initiator ports that will be used to connect the system to the switch."
---
= Obtaining WWPNs manually
:icons: font
:imagesdir: ../media/

[.lead]
If the ONTAP system is not connected to the SAN switch, you need to obtain the World Wide Port Names (WWPNs) of the system's FC initiator ports that will be used to connect the system to the switch.

Having the switch automatically discover WWPNs is the preferred method of obtaining WWPNs because you can avoid potential errors resulting from typing the WWPNs into the switch configuration.

.Steps
. Connect the system's console connection to a laptop computer.
. Power on your system.
+
Interrupt the boot process by pressing Ctrl-c when you see the following message on the console:
+
----
Press CTRL-C for boot menu
----

. Select the Maintenance Mode option on the boot options menu.
. Enter the following command to list the WWPNs of the system's FC initiator ports: `storage show adapter`
+
To list a specific adapter WWPN, add the adapter name, for example, storage show adapter 0a.

. Record the WWPNs that will be used and exit the Maintenance mode.
