---
permalink: install/task_configuring_lun_security.html
sidebar: sidebar
keywords: configure, lun, security
summary: "The storage array administrator must configure the storage array and create host groups so that other hosts cannot access the array LUNs intended for use by ONTAP."
---
= Configuring LUN security
:icons: font
:imagesdir: ../media/

[.lead]
The storage array administrator must configure the storage array and create host groups so that other hosts cannot access the array LUNs intended for use by ONTAP.

The concept of LUN security is similar to zoning except that LUN security is set up on the storage array. LUN security keeps different servers from using each other's storage on the SAN. LUN security might also be referred to as _LUN masking_.

.Steps
. Set up LUN security on the storage array.
+
Refer to the storage array documentation for information about setting up the LUN security.
+
You should also see https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html[FlexArray virtualization implementation for third-party storage] for any additional details regarding LUN security for your vendor's storage arrays. Some storage arrays must be dedicated for use by ONTAP systems.

. Create host groups, or the equivalent, for the ONTAP system.
+
The term _host group_ is used on some storage arrays to describe a configuration parameter that enables you to specify host access to specific ports on the storage array. Different storage arrays use different terms to describe this configuration parameter. Each storage array vendor has its own process for creating a host group or the equivalent.

*Related information*

// 2022 Dec 05, ONTAPDOC-717
