---
permalink: implement-third-party/concept_requirements_for_using_disks_external_to_the_storage_array.html
sidebar: sidebar
keywords: requirements, using, disks, external, storage, array
summary: "ONTAP supports using the same disks behind the storage arrays that the vendor supports (that is, disks external to the storage array). When you are deploying storage arrays that use external disks, ONTAP accepts the configuration between the storage array and the external disks."
---
= Requirements for using disks external to the storage array
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP supports using the same disks behind the storage arrays that the vendor supports (that is, disks external to the storage array). When you are deploying storage arrays that use external disks, ONTAP accepts the configuration between the storage array and the external disks.

The following are restrictions and best practice recommendations for deploying storage arrays that use external disks:

* Root volumes and spare core LUNs are supported on external disks.
* Array LUNs from external and internal disks should not be in the same ONTAP aggregate.
* Array LUNs from SATA drives and array LUNs from FC drives should not be in the same aggregate.
* Rules for the number of paths to array LUNs on external disks are the same as for array LUNs on disks on the storage array.
+
In the case of external disks, the paths go from the ONTAP system through the storage array to the external disks.

* Only block checksum is supported for array LUNs on external disks.

*Related information*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html[FlexArray virtualization installation requirements and reference]
