---
permalink: implement-third-party/concept_emc_vnx_storage_array_families.html
sidebar: sidebar
keywords: 
summary: 'ONTAP does not support mixing some types of storage in aggregates. To help you determine the array LUNs that can be mixed in an aggregate, the storage arrays from each vendor are grouped into families. When you create aggregates, you cannot mix array LUNs from different vendors and from different storage array families in the same aggregate.'
---
= EMC VNX storage array families
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP does not support mixing some types of storage in aggregates. To help you determine the array LUNs that can be mixed in an aggregate, the storage arrays from each vendor are grouped into families. When you create aggregates, you cannot mix array LUNs from different vendors and from different storage array families in the same aggregate.

Storage arrays in the same family share the same performance and failover characteristics. For example, members of the same family all perform active-active failover, or they all perform active-passive failover. More than one factor might be used to determine storage array families. For example, storage arrays with different architectures would be in different families even though other characteristics might be the same.

The following EMC VNX storage array families are supported with ONTAP systems:

* Family 1: VNX1
* Family 2: VNX2

These arrays use the asymmetric active-active (ALUA) failover mode.

The Interoperability Matrix is the final authority for information about the storage arrays supported for each vendor.

*Related information*

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
