---
permalink: implement-third-party/reference_workaround_when_luns_are_not_visible_with_hp_xp_storage_arrays.html
sidebar: sidebar
keywords: 
summary: 'The storage array parameters specified in the Required parameters for HP XP storage arrays with ONTAP systems section should be set and LUNs should be mapped to the host groups before the switch is zoned to connect the ONTAP system that uses array LUNs to an HP XP storage array.'
---
= Workaround when LUNs are not visible with HP XP storage arrays
:icons: font
:imagesdir: ../media/

[.lead]
The storage array parameters specified in the Required parameters for HP XP storage arrays with ONTAP systems section should be set and LUNs should be mapped to the host groups before the switch is zoned to connect the ONTAP system that uses array LUNs to an HP XP storage array.

xref:reference_required_parameters_for_hp_xp_storage_arrays_with_data_ontap_systems.adoc[Required parameters for HP XP storage arrays with ONTAP systems]

If zoning was configured prior to setting the parameters and mapping the LUNs to the host groups, you can resolve the problem of LUNs not being visible by -performing a path reinitialization. The path reinitialization forces a rediscovery of the array LUNs that are mapped from a HP XP storage array.

The procedure you use depends on whether aggregates with HP XP array LUNs have already been configured on the ONTAP system. (In the following procedures, assume that Node-1 and Node-2 are the names of the ONTAP nodes.)

== If aggregates with HP XP array LUNs are already created on an ONTAP system that uses array LUNs

. Run the following command to ensure that HA configuration is enabled on your ONTAP systems: `cluster ha show`
+
The following output is displayed:
+
----

High Availability Configured: true
----

. Run the following command to ensure that storage failover is configured on your ONTAP systems: `storage failover show`
+
The following output is displayed:
+
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-1    Node-2    true     Connected to Node-2
Node-2    Node-1    true     Connected to Node-1
2 entries were displayed.
----

. Perform a takeover operation on Node-1 by running the following command: `storage failover takeover -ofnode Node-1`
. Run the following command again to verify that Node-2 is ready for a giveback operation: `storage failover show`
+
The following output is displayed:
+
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-2    Node-1    false    In takeover, Auto giveback will be
                                      initiated in 348 seconds
Node-1    Node-2    -        Waiting for giveback (HA mailboxes)
2 entries were displayed.
----

. Perform a giveback operation on Node-1 by running the following command: `storage failover giveback -ofnode Node-1 -require-partner-waiting true`
. From other nodes in the cluster, repeat Step 3 through Step 5.

== If aggregates with HP XP array LUNs have not been created on an ONTAP systems that uses array LUNs

. Run the following command to list all the ONTAP FC initiator ports that are connected to the HP XP storage array: `system node run -node <node name> -command "sysconfig -v"`
+
For example: `system node run -node Node-1 -command "sysconfig -v"`

. Run the following command to take all the listed ports offline: `system node run -node <node name> -command "priv set advanced;fcadmin offline <adapter>"`
+
For example: `system node run -node Node-1 -command "priv set advanced;fcadmin offline 0a"`

. Run the following command to bring all the listed ports online: `system node run -node <node name> -command "priv set advanced;fcadmin online <adapter>"`
+
For example: `system node run -node Node-1 -command "priv set advanced;fcadmin online 0a"`
